Vagrant.configure("2") do |config|
    # Define the Windows VMs
    config.vm.define "W1VM" do |w1|
        w1.vm.box = "gusztavvargadr/windows-10"
        w1.vm.box_version = "2202.0.2302"
        w1.vm.hostname = "windows1VM"
        w1.vm.network "private_network", ip: "192.168.72.2"
        w1.vm.provider "virtualbox" do |vb|
            vb.name = "windows1VM"
            vb.gui = true
            vb.memory = "8192"
        end
    end
    
        
    config.vm.define "W2VM" do |w2|
        w2.vm.box = "gusztavvargadr/windows-10"
        w2.vm.box_version = "2202.0.2302"
        w2.vm.hostname = "windows2VM"
        w2.vm.network "private_network", ip: "192.168.72.46"
        w2.vm.provider "virtualbox" do |vb|
            vb.name = "windows2VM"
            vb.gui = true
            vb.memory = "8192"
        end
    end
  
    config.vm.define "linux1VM" do |l1|
        l1.vm.box = "ubuntu/bionic64"
        l1.vm.hostname = "linux1VM"
        l1.vm.network "private_network", ip: "192.168.72.28"
        l1.vm.provider "virtualbox" do |vb|
            vb.name = "linux1VM"
            vb.gui = true
            vb.memory = "8192"
        end
        l1.vm.provision "shell", inline: "sudo apt-get update"
      end
    
      config.vm.define "linux2VM" do |l2|
        l2.vm.box = "ubuntu/bionic64"
        l2.vm.hostname = "linux2VM"
        l2.vm.network "private_network", ip: "192.168.72.39"
        l2.vm.provider "virtualbox" do |vb|
            vb.name = "linux2VM"
            vb.gui = true
            vb.memory = "8192"
        end
        l2.vm.provision "shell", inline: "sudo apt-get update"
    end
end
  