Vagrant.configure("2") do |config|
    # Define the Windows VMs
    config.vm.define "windows1" do |windows1|
        windows1.vm.box = "generic/windows"
        windows1.vm.hostname = "windows1"
        windows1.vm.network "private_network", ip: "192.168.72.10"
        windows1.vm.provision "file", source: "target.exe", destination: "C:/target.exe"
        windows1.vm.provision "shell", inline: "Start-Process -FilePath 'C:/target.exe'"
    end
  
    config.vm.define "windows2" do |windows2|
        windows2.vm.box = "generic/windows"
        windows2.vm.hostname = "windows2"
        windows2.vm.network "private_network", ip: "192.168.72.11"
        windows2.vm.provision "file", source: "target.exe", destination: "C:/target.exe"
        windows2.vm.provision "shell", inline: "Start-Process -FilePath 'C:/target.exe'"
    end
    # Define the Linux VMs
    config.vm.define "linux1" do |linux1|
        linux1.vm.box = "generic/ubuntu1804"
        linux1.vm.hostname = "linux1"
        linux1.vm.network "private_network", ip: "192.168.72.20"
        linux1.vm.provision "file", source: "target.exe", destination: "/home/vagrant/target.exe"
        linux1.vm.provision "shell", inline: "chmod +x /home/vagrant/target.exe && /home/vagrant/target.exe &"
    end

    config.vm.define "linux2" do |linux2|
        linux2.vm.box = "generic/ubuntu1804"
        linux2.vm.hostname = "linux2"
        linux2.vm.network "private_network", ip: "192.168.72.21"
        linux2.vm.provision "file", source: "target.exe", destination: "/home/vagrant/target.exe"
        linux2.vm.provision "shell", inline: "chmod +x /home/vagrant/target.exe && /home/vagrant/target.exe &"
    end
  end
  